name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List files
        run: ls -R  # Helps verify the correct directory structure

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f BACKEND/Dockerfile BACKEND --push

      - name: Build and push Frontend Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f FRONTEND/Dockerfile FRONTEND --push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull and run Backend container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker run -d -p 5000:5000 --name backend ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Pull and run Frontend container
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker run -d -p 80:80 --name frontend ${{ secrets.DOCKER_USERNAME }}/frontend:latest
